{% set version = "0.5.6" %}
{% set name = "fpylll" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fplll/fpylll/releases/download/{{ version }}/fpylll-{{ version }}.tar.gz
  sha256: c69bf4b3344f60ca40743af9b9246ce51f651c2cf54d2b88a4deff18b1b5f246

build:
  number: 0
  skip: true  # [win]
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - cython
    - gmp
    - mpfr
    - qd
    - fplll >=5.4.0
    - cysignals
    - numpy
    - python
    - pip
  run:
    - gmp
    - mpfr
    - qd
    - fplll
    - cysignals
    - {{ pin_compatible('numpy') }}
    - python

test:
  requires:
    - pytest
  commands:
    - py.test --disable-pytest-warnings
  imports:
    - fpylll
  source_files:
    - tests/*

about:
  home: https://github.com/fplll/fpylll
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: A Python (2 and 3) wrapper for fplll.
  dev_url: https://github.com/fplll/fpylll

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
