{% set version = "0.5.1dev" %}
{% set name = "fpylll" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fplll/fpylll/releases/download/{{ version }}/fpylll-{{ version }}.tar.gz
  sha256: 5bc4640235d99abb1cc99ccca2368a1a94722e45cae8689aecbf17bc1508d8a2

build:
  number: 3
  skip: true  # [win]
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - cython
    - gmp
    - mpfr
    - qd
    - fplll >=5.3.3
    - cysignals
    - numpy
    - python
    - pip
  run:
    - gmp
    - mpfr
    - qd
    - fplll
    - cysignals
    - {{ pin_compatible('numpy') }}
    - python

test:
  requires:
    - pytest
  commands:
    - py.test --disable-pytest-warnings
  imports:
    - fpylll
  source_files:
    - tests/*

about:
  home: https://github.com/fplll/fpylll
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: A Python (2 and 3) wrapper for fplll.
  dev_url: https://github.com/fplll/fpylll

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
